INSERT INTO Department VALUES ("1","Computer Science");
INSERT INTO Department VALUES ("2","Electrical Engineering");
INSERT INTO Department VALUES ("3","Mechanical Engineering");
INSERT INTO Department VALUES ("4","Civil Engineering");
INSERT INTO Department VALUES ("5","Mathematics");
INSERT INTO Department VALUES ("6","Physics");
INSERT INTO Department VALUES ("7","Chemistry");
INSERT INTO Department VALUES ("8","Biotechnology");
INSERT INTO Department VALUES ("9","Information Systems");
INSERT INTO Department VALUES ("10","Data Science");
INSERT INTO Department VALUES ("11","Business Analytics");
INSERT INTO Department VALUES ("12","Economics");
INSERT INTO Department VALUES ("13","Psychology");
INSERT INTO Department VALUES ("14","Aerospace Engineering");
INSERT INTO Department VALUES ("15","Robotics");
INSERT INTO Department VALUES ("16","AI & Machine Learning");
INSERT INTO Department VALUES ("17","Biomedical Engineering");
INSERT INTO Department VALUES ("18","Material Science");
INSERT INTO Department VALUES ("19","Statistics");
INSERT INTO Department VALUES ("20","Cybersecurity");
